$SMTP_SERVER = "192.168.3.254"
$EMAIL_FROM = "IT-Team@intimetec.com"
$CC = "arunkumar.sundarrajan@intimetec.com"
$SUBJECT = "Change Password"
$TODAY = Get-Date
$FILENAME = $TODAY.ToString().Replace(" ","_").Replace("-","_").Replace(":","_")+".csv"
$EXPIRED_IN_DAYS = 60
$NOTIFICATION_SEND_BEFORE_DAYS = 7
$NOTIFIED_USER_LIST = @()
$EMAIL_BODY = ""

##### Get all enabled users from Active directory and whose Password Expired flag is false
$Users = get-aduser -filter {(Enabled -eq $true) -and (PasswordExpired -eq $false)} -Properties Name, PasswordNeverExpires, PasswordExpired, PasswordLastSet, EmailAddress

#### Traverse each user details
foreach($User in $Users)
{
    $ExpireOn = $User.PasswordLastSet.AddDays($EXPIRED_IN_DAYS)
    $LastPasswordSetAndExpireOnTimeDiff = New-TimeSpan -Start $TODAY -End $ExpireOn
    $RemainingDaysToExpire = $LastPasswordSetAndExpireOnTimeDiff.Days
    if($RemainingDaysToExpire -lt 0)
    {
        $User | Add-Member -MemberType NoteProperty -Name "ExpireOn" -Value "Expired" -Force
        $User | Select-Object Name,EmailAddress,ExpireOn,PasswordLastSet,PasswordNeverExpires| Export-Csv -Append -Path "C:\Users\yashwant.mahawar\Desktop\Data$FILENAME" -Force
        $NOTIFIED_USER_LIST+=$User
    }
    elseif($RemainingDaysToExpire -ge 0 -and $RemainingDaysToExpire -le $NOTIFICATION_SEND_BEFORE_DAYS)
    {
        if($RemainingDaysToExpire -eq 0)
        {
            $User | Add-Member -MemberType NoteProperty -Name "ExpireOn" -Value "Expire Today" -Force
        }
        else
        {
            $User | Add-Member -MemberType NoteProperty -Name "ExpireOn" -Value "Expire in $RemainingDaysToExpire days" -Force
        }
        $NOTIFIED_USER_LIST+=$User
        $User | Select-Object Name,EmailAddress,ExpireOn,PasswordLastSet,PasswordNeverExpires| Export-Csv -Append -Path "C:\Users\yashwant.mahawar\Desktop\Data$FILENAME" -Force
    }
}

foreach($User in $NOTIFIED_USER_LIST)
{
    $EMAIL_BODY = "Hi "+$User.Name+",<br><br>Your password "+$User.ExpireOn+" Please change it as soon as possible<br><br>It is a autogenerated mail please do not reply<br><br>Thanks<br>IT-Team"
    
        if($User.EmailAddress -ne $null)
        {
            if(-not ($User.EmailAddress).ToString().StartsWith("Health"))
            {
                Write-Host "mail send"+$user.Name
                Send-MailMessage -SmtpServer $SMTP_SERVER -Body $EMAIL_BODY -To $User.EmailAddress -Cc $CC -BodyAsHtml -Priority High -From $EMAIL_FROM -Subject $SUBJECT
            }
            
        }
    
}